#!/bin/sh

B="\x1b[1m"
C="\x1b[0m"
GRN="\x1b[32m"
YEL="\x1b[33m"
BLU="\x1b[34m"
OSU="\x1b[38;2;238,49,122m"
col2="$BLU::$C"

osu_url=https://github.com/ppy/osu
current=`cat current_version`
echo -e "$col2 Getting latest version..." >/dev/stderr
latest=`basename $(curl -Ls -o /dev/null -w %{url_effective} "$osu_url/releases/latest")`

if [ "$current" = "$latest" ] && [ "$1" != "-f" ]; then
  echo -e "$col2 Current $GRN$current$C is latest, no update required" >/dev/stderr
  exit 1
fi

echo -e "$col2 Update required from $YEL$current$C to $GRN$latest$C"
echo -e "$col2 Downloading latest $B${OSU}osu!lazer$C archive..."
appimage="osu-lazer-bin-$latest.AppImage"
curl "$osu_url/releases/download/$latest/osu.AppImage" -Lo "$appimage"

echo -e "$col2 Writing current version and sha256sum..."
echo -e "$latest" >current_version
sha256sum "$appimage" | cut -d' ' -f1 >osu_sha256sum

echo -e "$col2 Writing .SRCINFO file..."
makepkg --printsrcinfo > .SRCINFO

echo -e "$col2 Done"
